# Assignment 4


Ques 1)Write a program to create a NumPy 1D-array with 5 elements and perform basic
operations like:
1. Addition of 2 in all the element
2. Multiply 3 with all the elements
3. Divide every element by 2

In [3]:
import numpy as np

a = [1,2,3,4,5]
arr = np.array(a)

print(f"1. {arr[1] + arr[2]}")
print(f"2. {arr * 3}")
print(f"3. {arr / 2}")


1. 5
2. [ 3  6  9 12 15]
3. [0.5 1.  1.5 2.  2.5]


Ques2) Questions on Basic NumPy Array: <br>
a. Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5]) <br>
b. Find the most frequent value and their indice(s) in the following arrays: <br>
    i. x = np.array([1,2,3,4,5,1,2,1,1,1])  <br>
    ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [5]:
import numpy as np 
arr = np.array([1,2,3,4,5])
print(f"Reversed array: {np.flip(arr)}")

Reversed array: [5 4 3 2 1]


Ques3) For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access
elements using row and column indices as follows:
a) Access 1st row, 2nd column
b) Access 3rd row, 1st column

In [7]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print("(a) 1st row, 2nd column:", arr[0, 1])  
print("(b) 3rd row, 1st column:", arr[2, 0])  

(a) 1st row, 2nd column: 20
(b) 3rd row, 1st column: 70


Ques4) Write program to create an 1-D NumPy array named <<Your Name>> with evenly
spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array,
shape, total elements, the data type of each element and total number of bytes consumed
by the array. Find the transpose of this array using reshape() attribute. Can we do the same
with T attribute?

In [9]:
AAYUSHMAN_SINGH_CHANDEL = np.linspace(10, 100, 25)
print("\nArray:", AAYUSHMAN_SINGH_CHANDEL)
print("Dimensions:", AAYUSHMAN_SINGH_CHANDEL.ndim)
print("Shape:", AAYUSHMAN_SINGH_CHANDEL.shape)
print("Total Elements:", AAYUSHMAN_SINGH_CHANDEL.size)
print("Data Type:", AAYUSHMAN_SINGH_CHANDEL.dtype)
print("Total Bytes Consumed:", AAYUSHMAN_SINGH_CHANDEL.nbytes)

transposed_array = AAYUSHMAN_SINGH_CHANDEL.reshape(25, 1)  
print("\nReshaped (Transpose using reshape):\n", transposed_array)
print("Transpose using T attribute:\n", AAYUSHMAN_SINGH_CHANDEL.T)


Array: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions: 1
Shape: (25,)
Total Elements: 25
Data Type: float64
Total Bytes Consumed: 200

Reshaped (Transpose using reshape):
 [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
Transpose using T attribute:
 [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


Ques5) Create a 2-D Array of three rows and four columns, named ucs420_<your_name>>
with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean,
median, max, min, unique elements. Reshape the array to four rows and three columns and
name it as reshaped_ ucs420_<your_name>>. Resize the array to two rows and three
columns and name it as resized_ ucs420_<your_name>>.

In [11]:
ucs420_AAYUSHMAN_SINGH_CHANDEL = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 15, 20, 35]])
print("\nMean:", np.mean(ucs420_AAYUSHMAN_SINGH_CHANDEL))
print("Median:", np.median(ucs420_AAYUSHMAN_SINGH_CHANDEL))
print("Max:", np.max(ucs420_AAYUSHMAN_SINGH_CHANDEL))
print("Min:", np.min(ucs420_AAYUSHMAN_SINGH_CHANDEL))
print("Unique Elements:", np.unique(ucs420_AAYUSHMAN_SINGH_CHANDEL))


reshaped_ucs420_AAYUSHMAN_SINGH_CHANDEL = ucs420_AAYUSHMAN_SINGH_CHANDEL.reshape(4, 3)
print("\nReshaped to 4x3:\n", reshaped_ucs420_AAYUSHMAN_SINGH_CHANDEL)


resized_ucs420_AAYUSHMAN_SINGH_CHANDEL = ucs420_AAYUSHMAN_SINGH_CHANDEL[:2, :3]  
print("\nResized to 2x3:\n", resized_ucs420_AAYUSHMAN_SINGH_CHANDEL)


Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique Elements: [10 15 20 30 35 40 50 60 70 80 90]

Reshaped to 4x3:
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]

Resized to 2x3:
 [[10 20 30]
 [50 60 70]]
